import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/theme-provider";
import type { ReactNode } from "react";
import AuthProvider from "@/components/providers/AuthProvider";
import { CartSync } from "@/features/cart/components/CartSync";
import { Toaster } from "@/components/ui/sonner";
import { ShopSettingsProvider } from "@/components/providers/ShopSettingsProvider";
import { getShopSettings } from "@/lib/shop-settings.server";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Z Factor Studio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: {children:ReactNode}) {
  // Store rules from Admin → Settings, for client components.
  const shopSettings = await getShopSettings();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ShopSettingsProvider settings={shopSettings}>
          <AuthProvider>
          {children}
          <CartSync />
          </AuthProvider>
          <Toaster />
          </ShopSettingsProvider>
          </Providers>
      </body>
    </html>
  );
}
