import type { Metadata } from "next";
import { Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/theme-provider";
import type { ReactNode } from "react";
import AuthProvider from "@/components/providers/AuthProvider";
import { CartSync } from "@/features/cart/components/CartSync";
import { Toaster } from "@/components/ui/sonner";
import { ShopSettingsProvider } from "@/components/providers/ShopSettingsProvider";
import { getShopSettings } from "@/lib/shop-settings.server";


// Fonts are downloaded at build time and served with the site (no request
// to Google, no text jump when they load). Used via --font-sans/--font-mono
// in globals.css.
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Z Factor Studio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: {children:ReactNode}) {
  // Store rules from Admin → Settings, for client components.
  const shopSettings = await getShopSettings();

  return (
    <html lang="en" className={`${manrope.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <ShopSettingsProvider settings={shopSettings}>
          <AuthProvider>
          {children}
          <CartSync />
          </AuthProvider>
          <Toaster />
          </ShopSettingsProvider>
          </Providers>
      </body>
    </html>
  );
}
