import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers/theme-provider";
import type { ReactNode } from "react";
import AuthProvider from "@/components/providers/AuthProvider";
import { CartSync } from "@/features/cart/components/CartSync";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Z Factor Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children:ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <AuthProvider>
          {children}
          <CartSync />
          </AuthProvider>
          </Providers>
      </body>
    </html>
  );
}
